void abertura();
void chuta();
int jachutou(char letra);
void desenhaforca();
void escolhepalavra();
int enforcou();
int acertou();
void adcionapalvra();
int chuteserrados();
int letraexiste(char letra);
int ganhou();